name: Build and Push Docker Image to Docker Hub
permissions:
  #contents: read
  #pages: write
  id-token: write
env:
    IMAGE_NAME: makremzitoun/netcore-api
  
on: push
#workflow_dispatch
jobs:
  push_to_registry:
    name: push docker image to hub
    runs-on: ubuntu-latest
    steps:
      - name: check repository
        uses: actions/checkout@v4

      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USR}}
          password: ${{secrets.DOCKERHUB_TKN}}

      - name: build and push docker image to registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.run_number }}, ${{ env.IMAGE_NAME }}:latest
          file: ./Dockerfile
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          #creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
          client-id: '${{ secrets.AZURE_CLIENT_ID }}' 
          tenant-id:  '${{ secrets.AZURE_TENANT_ID }}'
          subscription-id: '${{ secrets.AZURE_SUBSCRIPTION_ID }}'
      - name: 'Run az commands'
        run: |
          az acr list 
          #--query "[?contains(resourceGroup, 'mslearn-gh-pipelines')].loginServer" -o table
      - name: 'Create RG'
        run: |   
          az group create --name AzureRG --location eastus
      
      - name: 'Create ACR'
        run: | 
          az acr create --resource-group AzureRG --name dotnetaksdemo --sku Basic
          
      - name: 'Create ACR1'
        run: | 
         docker build -t dotnetaksdemo.azurecr.io/dotnetapi-aks-app:latest     
