name: eShopOnWeb Build and Test

#Triggers (uncomment line below to use it)
on: [push, workflow_dispatch]

#Environment variables https://docs.github.com/en/actions/learn-github-actions/environment-variables

jobs:
  #Build, test and publish .net web project in repository
  buildandtest:
    runs-on: ubuntu-latest
    steps:
    #checkout the repository
    - uses: actions/checkout@v4
    #prepare runner for desired .net version SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    #Build/Test/Publish the .net project
    - name: Build with dotnet
      run: dotnet build ./WebApplication1.sln --configuration Release
    - name: Test with dotnet
      run: dotnet test ./WebApplication1.sln --configuration Release
    - name: dotnet publish
      run: |
        dotnet publish ./WebApplication1.csproj -c Release -o .net-app/myapp
        cd .net-app/myapp
        zip -r ../app.zip .
    # upload the published website code artifacts
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: .net-app
        path: .net-app/app.zip
    
  deploy:
    runs-on: ubuntu-latest
    needs: buildandtest
    environment:
      name: 'Devloppement'
    steps:
    
    #Download the publish files created in previous job
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: .net-app
        path: .net-app
        
