name: Deploy .NET Core API to AKS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Build the API
      run: dotnet build --configuration Release

    # Log in to Azure CLI to authenticate with ACR
    - name: Azure CLI Login
      run: |
        echo "${{ secrets.AZURE_CREDENTIALS }}" > azure_credentials.json
        az login --service-principal -u "${{ secrets.AZURE_CLIENT_ID }}" -p "${{ secrets.AZURE_CLIENT_SECRET }}" --tenant "${{ secrets.AZURE_TENANT_ID }}"
    
    # Azure Container Registry (ACR) Creation
    - name: ACR Create
      run: |
        az acr create --resource-group myResourceGroup --name dotnetaksdemo --sku Basic
    
    # Azure Container Registry (ACR) login
    - name: ACR Login
      run: |
        az acr login --name dotnetaksdemo.azurecr.io

    # Build and push Docker image to ACR
    - name: Build and push Docker image to ACR
      run: |
        docker build -t dotnetaksdemo.azurecr.io.azurecr.io/my-api:${{ github.sha }} .
        docker push dotnetaksdemo.azurecr.io.azurecr.io/my-api:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up kubectl
    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    # Authenticate to Azure and get AKS credentials
    - name: Configure kubectl
      run: |
        echo "${{ secrets.AZURE_CREDENTIALS }}" > azure_credentials.json
        az login --service-principal -u "${{ secrets.AZURE_CLIENT_ID }}" -p "${{ secrets.AZURE_CLIENT_SECRET }}" --tenant "${{ secrets.AZURE_TENANT_ID }}"
        az aks get-credentials --resource-group myResourceGroup --name myAKSCluster

    # Deploy the new image to AKS
    #- name: Deploy to AKS
     # run: |
      #  kubectl set image deployment/my-api-deployment my-api-container=${{ secrets.ACR_NAME }}.azurecr.io/my-api:${{ github.sha }}
