name: Deploy .NET Core API to AKS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Build the API
      run: dotnet build --configuration Release

    # Log in to Azure CLI to authenticate with ACR
    - name: Azure CLI Login
      run: |
        echo "${{ secrets.AZURE_CREDENTIALS }}" > azure_credentials.json
        az login --service-principal -u "${{ secrets.AZURE_CLIENT_ID }}" -p "${{ secrets.AZURE_CLIENT_SECRET }}" --tenant "${{ secrets.AZURE_TENANT_ID }}"
    
    # Azure Container Registry (ACR) Creation
    - name: ACR Create
      run: |
        az acr create --resource-group myResourceGroup --name dotnetaksdemo --sku Basic
    
    # Azure Container Registry (ACR) login
    - name: ACR Login
      run: |
        az acr login --name dotnetaksdemo.azurecr.io

    # Build and push Docker image to ACR
    - name: Build and push Docker image to ACR
      run: |
        docker build -t dotnetaksdemo.azurecr.io/my-api:latest .
        docker push dotnetaksdemo.azurecr.io/my-api:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up kubectl
    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    # Authenticate to Azure and get AKS credentials
    - name: Configure kubectl
      run: |
        echo "${{ secrets.AZURE_CREDENTIALS }}" > azure_credentials.json
        az login --service-principal -u "${{ secrets.AZURE_CLIENT_ID }}" -p "${{ secrets.AZURE_CLIENT_SECRET }}" --tenant "${{ secrets.AZURE_TENANT_ID }}"
        az aks get-credentials --resource-group myResourceGroup --name myAKSCluster
        az aks update -n myAKSCluster -g myResourceGroup --attach-acr dotnetaksdemo
        az role assignment create --assignee "${{ secrets.AZURE_CLIENT_ID }}" --role AcrPull --scope /subscriptions/21820b91-3cd2-4b83-a038-2545bf88960c/resourceGroups/myResourceGroup/providers/Microsoft.ContainerRegistry/registries/myAKSCluster
        az role assignment create --assignee "${{ secrets.AZURE_CLIENT_ID }}" --role Contributor --scope /subscriptions/21820b91-3cd2-4b83-a038-2545bf88960c/resourceGroups/myResourceGroup



    # Deploy the new image to AKS
    - name: Deploy to AKS
      run: |
       kubectl get nodes
       kubectl apply -f ./deployPod.yaml
      # kubectl set image deployment/my-api-deployment my-api-container=dotnetaksdemo.azurecr.io/my-api:${{ github.sha }}
